// randomUsernames.ts

const adjectives = [
  "Ruthless",
  "Devious",
  "Ostracized",
  "Wicked",
  "Suffering",
  "Mischievous",
  "Immoral",
  "Stingy",
  "Abandoned",
  "Feral",
  "Ungrateful",
  "Homeless",
  "Melancholic",
  "Rebellious",
  "Heretical",
  "Treasonous",
  "Fugitive",
  "Cynical",
  "Unpredictable",
  "Doubtful",
  "Pessimistic",
  "Impoverished",
  "Sacrilegious",
  "Incarcerated",
  "Deserted",
  "Provocative",
  "Rowdy",
  "Iconoclastic",
  "Apostate",
  "Foolish",
  "Clumsy",
  "Isolated",
  "Nihilistic",
  "Lawless",
  "Rapscallion",
  "Fraudulent",
  "Secluded",
  "Scapegoated",
  "Deceptive",
  "Usurping",
  "Nomadic",
  "Roaming",
  "Fanatical",
  "Agitating",
  "Deceitful",
  "Wandering",
  "Exiled",
];

const people = [
  "Miscreant",
  "Scoundrel",
  "Outcast",
  "Pariah",
  "Rascal",
  "Reprobate",
  "Miser",
  "Castaway",
  "Cur",
  "Ingrate",
  "Vagrant",
  "Renegade",
  "Heretic",
  "Fugitive",
  "Cynic",
  "Skeptic",
  "Pessimist",
  "Beggar",
  "Blasphemer",
  "Convict",
  "Deserter",
  "Felon",
  "Hooligan",
  "Nihilist",
  "Outlaw",
  "Recluse",
  "Trickster",
  "Vagabond",
  "Wanderer",
  "Zealot",
  "Agitator",
];

export const getRandomUsername = () => {
  const randomAdjective =
    adjectives[Math.floor(Math.random() * adjectives.length)];
  const randomPerson = people[Math.floor(Math.random() * people.length)];

  return `${randomAdjective} ${randomPerson}`;
};
